# This is a basic workflow to help you get started with Actions

name: Demo 6 - Testing self-hosted runners

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [disabled]    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hello-world:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
  mac-only:
    runs-on: [self-hosted, macOS]
    # Runs a set of commands using the runners shell
    steps:
      - name: Run a multi-line script
        run: |
          echo This step was run on MAC
          echo using [self-hosted, macOs]
  windows-only:
    runs-on: [self-hosted, Windows]
    steps:
      - name: Create a directory in _work wit PowerShell
        run: |
          If(!(test-path "this-is-a-test"))
          {
            New-Item -ItemType Directory -Force -Path "this-is-a-test"
          }
  mac-kubectl:
    runs-on: [self-hosted, macOs]
    steps:
      - name: Execute kubectl locally
        run: |
          kubectl get nodes
